name: 'tfsdwh'
version: '1.0'
config-version: 2

profile: 'tfsdwh'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  tfsdwh:

    # ----------------------------------------------------
    # STAGE MODELS (PER SOURCE SYSTEM)
    # ----------------------------------------------------
    stage:
      tiplus_as:
        +schema: STAGE_TIPLUS_AS
        +materialized: incremental
        +incremental_strategy: append

      tiplus_eu:
        +schema: STAGE_TIPLUS_EU
        +materialized: incremental
        +incremental_strategy: append

    # ----------------------------------------------------
    # RAW DATA VAULT (Hubs, Links, Satellites)
    # ----------------------------------------------------
    raw_vault:
      +schema: RAW_VAULT
      +materialized: incremental
      +incremental_strategy: append

    # ----------------------------------------------------
    # BUSINESS VAULT
    # ----------------------------------------------------
    business_vault:
      +schema: BUSINESS_VAULT
      +materialized: incremental
      +incremental_strategy: append

    # ----------------------------------------------------
    # ANALYTICS / DATA MARTS
    # ----------------------------------------------------
    analytics:
      +schema: ANALYTICS
      +materialized: view
