name: datastreaming

networks:
  oggnet: {}

volumes:
  sor-data:
  dwh-data:
  ogg-u01-ogg-scripts:
  ogg-u02:
  ogg-u03:
  dbt-project:

services:
  # -----------------------------
  # Source DB (SOR) - Oracle 19c
  # -----------------------------
  sor:
    image: oracle/database:19.3.0-ee
    container_name: sor
    environment:
      ORACLE_PWD: "tfsdwh_POC1"
      ORACLE_SID: "SORCDB"
      ORACLE_PDB: "SORPDB1"
    ports:
      - "1521:1521"
    volumes:
      - sor-data:/opt/oracle/oradata
      - ./database/sor/setup:/opt/oracle/scripts/setup:ro
      - ./database/sor/startup:/opt/oracle/scripts/startup:ro
      - ./database/sor/cleanup:/opt/oracle/scripts/cleanup:ro
    networks: [oggnet]
    restart: unless-stopped

  # -----------------------------
  # Target DB (DWH) - Oracle 19c
  # -----------------------------
  dwh:
    image: oracle/database:19.3.0-ee
    container_name: dwh
    environment:
      ORACLE_PWD: "tfsdwh_POC1"
      ORACLE_SID: "DWHCDB"
      ORACLE_PDB: "DWHPDB1"
    ports:
      - "1522:1521"
    volumes:
      - dwh-data:/opt/oracle/oradata
      - ./database/dwh/setup:/opt/oracle/scripts/setup:ro
      - ./database/dwh/startup:/opt/oracle/scripts/startup:ro
      - ./database/dwh/cleanup:/opt/oracle/scripts/cleanup:ro
    networks: [oggnet]
    restart: unless-stopped

  # --------------------------------------
  # Oracle GoldenGate 23 (Microservices)
  # --------------------------------------
  ogg23:
    image: oracle/goldengate:23.4
    container_name: ogg23
    platform: linux/amd64
    depends_on:
      - sor
      - dwh
    ports:
      - "18080:80"
      - "18443:443"
    environment:
      OGG_ADMIN: "oggadmin"
      OGG_ADMIN_PWD: "tfsdwh_POC1"
      OGG_DEPLOYMENT: "Local"
    networks: [oggnet]
    restart: unless-stopped
    volumes:
      - ogg-u01-ogg-scripts:/u01/ogg/scripts
      - ogg-u02:/u02
      - ogg-u03:/u03

  # --------------------------------------
  # dbt container (dbt-core + Oracle adapter)
  # --------------------------------------
  dbt:
    build: ./dbt
    container_name: dbt
    platform: linux/amd64
    depends_on:
      - dwh
    ports:
      - "8080:8080"
    environment:
      DBT_PROFILES_DIR: /root/.dbt
      TZ: Europe/Amsterdam
    volumes:
      - ./dbt:/usr/app/dbt
      - ./dbt/profiles:/root/.dbt
    working_dir: /usr/app/dbt
    networks: [oggnet]
    stdin_open: true
    tty: true
    entrypoint: ["/usr/app/dbt/entrypoint.sh"]