-- Run as SYSDBA

ALTER SESSION SET CONTAINER = SORPDB1;

PROMPT === Creating TIZONE Schema Owners ===

CREATE USER TIZONE1_OWNER IDENTIFIED BY &SOR_TIZONE1_OWNER_PASSWORD
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS
  ACCOUNT UNLOCK;

CREATE USER TIZONE2_OWNER IDENTIFIED BY &SOR_TIZONE2_OWNER_PASSWORD
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS
  ACCOUNT UNLOCK;

PROMPT === Granting Base Privileges to TIZONE Owners ===

GRANT CREATE SESSION,
      CREATE TABLE,
      CREATE SEQUENCE,
      CREATE PROCEDURE
      TO TIZONE1_OWNER;

GRANT CREATE SESSION,
      CREATE TABLE,
      CREATE SEQUENCE,
      CREATE PROCEDURE
      TO TIZONE2_OWNER;

PROMPT === TIZONE user creation completed ===
