tfsdwh:
  target: dev
  outputs:
    dev:
      type: oracle
      host: dwh
      port: 1521
      user: DWH_TIPLUS_DBT
      password: tfsdwh_POC1
      service: DWHPDB1
      database: DWHPDB1
      protocol: tcp
      threads: 4
      schema: DWH
