-- Run as SYSDBA

ALTER SESSION SET CONTAINER = DWHPDB1;

PROMPT === Creating DWH Landing Schemas ===

CREATE USER DWH_LANDING_TIPLUS_AS IDENTIFIED BY "&DWH_LANDING_TIPLUS_AS_PASSWORD"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

CREATE USER DWH_LANDING_TIPLUS_EU IDENTIFIED BY "&DWH_LANDING_TIPLUS_EU_PASSWORD"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

PROMPT === Creating DWH Stage Schemas ===

CREATE USER DWH_STAGE_TIPLUS_AS IDENTIFIED BY "&DWH_STAGE_TIPLUS_AS_PASSWORD"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

CREATE USER DWH_STAGE_TIPLUS_EU IDENTIFIED BY "&DWH_STAGE_TIPLUS_EU_PASSWORD"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

PROMPT === Creating Raw and Business Vault Schemas ===

CREATE USER DWH_RAW_VAULT IDENTIFIED BY "&DWH_RAW_VAULT_PASSWORD"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

CREATE USER DWH_BUSINESS_VAULT IDENTIFIED BY "&DWH_BUSINESS_VAULT_PASSWORD"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

PROMPT === Creating Analytics Schema ===

CREATE USER DWH_ANALYTICS IDENTIFIED BY "&DWH_ANALYTICS_PASSWORD"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

PROMPT === Granting Base Privileges to All DWH Schemas ===

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO DWH_LANDING_TIPLUS_AS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO DWH_LANDING_TIPLUS_EU;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO DWH_STAGE_TIPLUS_AS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO DWH_STAGE_TIPLUS_EU;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO DWH_RAW_VAULT;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO DWH_BUSINESS_VAULT;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO DWH_ANALYTICS;

PROMPT === Creating DBT User ===

CREATE USER DWH_DBT_USER IDENTIFIED BY "&DWH_DBT_USER_PASSWORD"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

PROMPT === Granting DBT Privileges ===

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO DWH_DBT_USER;
GRANT SELECT ANY TABLE TO DWH_DBT_USER;
GRANT CREATE ANY TABLE, CREATE ANY VIEW TO DWH_DBT_USER;
GRANT INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO DWH_DBT_USER;

PROMPT === DWH User and Privilege Setup Complete ===
