-- Run as SYSDBA

ALTER SESSION SET CONTAINER = DWHPDB1;

PROMPT === Dropping Landing Tables: TIPLUS AS ===

DROP TABLE DWH_LANDING_TIPLUS_AS.BASEEVENT CASCADE CONSTRAINTS PURGE;
DROP TABLE DWH_LANDING_TIPLUS_AS.MASTER    CASCADE CONSTRAINTS PURGE;

PROMPT === Dropping Landing Tables: TIPLUS EU ===

DROP TABLE DWH_LANDING_TIPLUS_EU.BASEEVENT CASCADE CONSTRAINTS PURGE;
DROP TABLE DWH_LANDING_TIPLUS_EU.MASTER    CASCADE CONSTRAINTS PURGE;

PROMPT === TIPLUS Landing table drop complete ===
