-- Run as SYSDBA

ALTER SESSION SET CONTAINER = DWHPDB1;

PROMPT === Dropping DWH users and schemas ===

DROP USER DWH_LANDING_TIPLUS_AS CASCADE;
DROP USER DWH_LANDING_TIPLUS_EU CASCADE;

DROP USER DWH_STAGE_TIPLUS_AS CASCADE;
DROP USER DWH_STAGE_TIPLUS_EU CASCADE;

DROP USER DWH_RAW_VAULT CASCADE;
DROP USER DWH_BUSINESS_VAULT CASCADE;
DROP USER DWH_ANALYTICS CASCADE;

DROP USER DWH_DBT_USER CASCADE;

PROMPT === Done: All DWH schemas dropped ===
