name: 'tfsdwh'
version: '1.0.0'

profile: 'tfsdwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# ---------------------------------------------------------
# MODEL CONFIGURATION
# ---------------------------------------------------------

models:
  tfsdwh:

    # -----------------------------------------------------
    # SOURCE EVENT, CURRENT AND STAGING
    # -----------------------------------------------------
    source:
      +schema: dwh_tiplus_source

      event:
        +materialized: incremental

      current:
        +materialized: incremental

      staging:
        +materialized: view

    # -----------------------------------------------------
    # DATA VAULT
    # -----------------------------------------------------
    datavault:
      hubs:
        +schema: dwh_datavault
        +materialized: incremental

      links:
        +schema: dwh_datavault
        +materialized: incremental

      sats:
        +schema: dwh_datavault
        +materialized: incremental