driver=oracle.jdbc.OracleDriver
#classpath=/liquibase/lib/ojdbc17.jar
url=jdbc:oracle:thin:@//dwh:1521/DWHPDB1
username=DWH_ANALYTICS
password=Welkome123
# Changelog file
changeLogFile=/liquibase/changelog/master.xml
# Optional settings
logLevel=info