-- Run as SYSDBA

ALTER SESSION SET CONTAINER = SORPDB1;

PROMPT === Dropping TIZONE Schema Owners ===

DROP USER TIZONE1_OWNER CASCADE;
DROP USER TIZONE2_OWNER CASCADE;

PROMPT === TIZONE user drop completed ===
