-- Run as SYSDBA

ALTER SESSION SET CONTAINER = SORPDB1;

PROMPT === Dropping TIZONE1 Tables ===

DROP TABLE TIZONE1_OWNER.BASEEVENT CASCADE CONSTRAINTS PURGE;
DROP TABLE TIZONE1_OWNER.MASTER    CASCADE CONSTRAINTS PURGE;

PROMPT === Dropping TIZONE2 Tables ===

DROP TABLE TIZONE2_OWNER.BASEEVENT CASCADE CONSTRAINTS PURGE;
DROP TABLE TIZONE2_OWNER.MASTER    CASCADE CONSTRAINTS PURGE;

PROMPT === TIZONE table drop complete ===
